# Startup applications

$scriptsDir = $HOME/.config/hypr/scripts

# D-Bus
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Polkit
exec-once = $scriptsDir/Polkit.sh

# Network & Bluetooth
exec-once = nm-applet --indicator
exec-once = blueman-applet

# Notifications
exec-once = swaync

# Quickshell (bar, launcher, components)
exec-once = qs

# Swww (wallpaper daemon)
exec-once = swww init

# Clipboard
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Idle / lockscreen
exec-once = hypridle
