# Default color palette (overwritten by set-wallpaper.sh via matugen)
$color0 = 1e1e1eff
$color1 = cf6679ff
$color2 = 03dac6ff
$color3 = bb86fcff
$color4 = 3700b3ff
$color5 = 018786ff
$color6 = 121212ff
$color7 = ffffffff
$color8 = 2d2d2dff
$color9 = ff7597ff
$color10 = 535353ff
$color11 = ffb74dff
$color12 = bb86fcff
$color13 = cf6679ff
$color14 = 03dac6ff
$color15 = ffffff80
