# Workspace configuration
workspace = 1, defaultName:1
workspace = 2, defaultName:2
workspace = 3, defaultName:3
workspace = 4, defaultName:4
workspace = 5, defaultName:5
workspace = 6, defaultName:6
workspace = 7, defaultName:7
workspace = 8, defaultName:8
workspace = 9, defaultName:9
workspace = 10, defaultName:10
