#!/usr/bin/env bash
# set-wallpaper.sh — canonical script
# Set wallpaper via swww and regenerate full theme
set +o pipefail

WALLPAPER="${1:-}"
WALL_DIR="${WALL_DIR:-$HOME/Pictures/Wallpapers}"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"

if [[ -z "$WALLPAPER" ]]; then
  echo "Usage: $0 <path-to-image>"
  echo "Pick from: $WALL_DIR"
  ls "$WALL_DIR" 2>/dev/null || echo "(no wallpapers found)"
  exit 1
fi

if [[ ! -f "$WALLPAPER" ]]; then
  echo "File not found: $WALLPAPER"
  exit 1
fi

# Set wallpaper with swww (non-fatal — may not be running)
swww img "$WALLPAPER" --transition-type wipe --transition-duration 1 2>/dev/null || true

# Regenerate matugen theme
if command -v matugen &>/dev/null; then
  echo "Generating color palette..."
  
  PALETTE=$(matugen image "$WALLPAPER" --prefer darkness --json hex 2>/dev/null) || true
  if [[ -z "$PALETTE" ]]; then
    echo "matugen failed — using fallback colors"
  else
    extract_hex() {
      echo "$PALETTE" | jq -r ".colors.$1.default.color // \"#$2\""
    }

    # ── Quickshell theme.json ───────────────────────────────────────────
    mkdir -p "$CONFIG_DIR/quickshell"
    cat > "$CONFIG_DIR/quickshell/theme.json" <<- THEME
{
  "window_background": "$(extract_hex surface '#121212')",
  "primary_text": "$(extract_hex on_surface '#ffffff')",
  "layer_background_1": "$(extract_hex surface_container '#1e1e1e')",
  "layer_background_2": "$(extract_hex surface_container_high '#2d2d2d')",
  "layer_background_3": "$(extract_hex surface_container_highest '#383838')",
  "surface_text": "$(extract_hex on_surface '#e0e0e0')",
  "secondary_text": "$(extract_hex on_surface_variant '#b0b0b0')",
  "border_primary": "$(extract_hex primary '#bb86fc')",
  "shadow_color": "#000000",
  "accent_primary": "$(extract_hex primary '#bb86fc')",
  "accent_secondary": "$(extract_hex secondary '#03dac6')",
  "selection_background": "$(extract_hex primary_container '#534457')",
  "accent_primary_text": "$(extract_hex on_primary '#000000')",
  "selection_text": "#ffffff",
  "border_secondary": "$(extract_hex outline '#555555')",
  "error": "$(extract_hex error '#cf6679')"
}
THEME
    echo "  theme.json written"

    # ── Hyprland colors.conf ────────────────────────────────────────────
    mkdir -p "$CONFIG_DIR/hypr"
    cat > "$CONFIG_DIR/hypr/colors.conf" <<- HYPR
# Auto-generated by matugen
\$color0 = $(extract_hex surface '#1e1e1e' | tr -d '#')ff
\$color1 = $(extract_hex error '#cf6679' | tr -d '#')ff
\$color2 = $(extract_hex secondary '#03dac6' | tr -d '#')ff
\$color3 = $(extract_hex primary '#bb86fc' | tr -d '#')ff
\$color4 = $(extract_hex primary_container '#3700b3' | tr -d '#')ff
\$color5 = $(extract_hex secondary_container '#018786' | tr -d '#')ff
\$color6 = $(extract_hex surface '#121212' | tr -d '#')ff
\$color7 = $(extract_hex on_surface '#ffffff' | tr -d '#')ff
\$color8 = $(extract_hex surface_variant '#2d2d2d' | tr -d '#')ff
\$color9 = $(extract_hex on_error '#ff7597' | tr -d '#')ff
\$color10 = $(extract_hex outline '#535353' | tr -d '#')ff
\$color11 = $(extract_hex tertiary '#ffb74d' | tr -d '#')ff
\$color12 = $(extract_hex primary '#bb86fc' | tr -d '#')ff
\$color13 = $(extract_hex error '#cf6679' | tr -d '#')ff
\$color14 = $(extract_hex secondary '#03dac6' | tr -d '#')ff
\$color15 = $(extract_hex on_surface '#ffffff' | tr -d '#')80
HYPR
    echo "  colors.conf written"
  fi

  # GTK theme via gtk.css template (if exists)
  if [[ -f "$CONFIG_DIR/matugen/templates/qs-gtk.css" ]]; then
    matugen image "$WALLPAPER" --type scheme-tonal-spot \
      --template qs-gtk \
      --output "$CONFIG_DIR/gtk-3.0/gtk.css" 2>/dev/null || true
    cp "$CONFIG_DIR/gtk-3.0/gtk.css" "$CONFIG_DIR/gtk-4.0/gtk.css" 2>/dev/null || true
  fi

  echo "Theme regenerated via matugen"
fi

# Write last wallpaper for persistence
echo "$WALLPAPER" > "$HOME/.cache/last-wallpaper"

# Notify
notify-send "Wallpaper set" "$(basename "$WALLPAPER")" 2>/dev/null || true
